### ISSUE TITLE
Could you support python 3.x?

### ISSUE THREAD

**Issue by renweibo** [parrt/lolviz#11]
It seems the package in pypi only support python 2.7. Is it compatible with python 3.x. If not, do you have any plan for that?

**Comment by parrt** [comment]
Dup of https://github.com/parrt/lolviz/issues/3 pushing 1.2.1 now.

**Comment by parrt** [comment]
Try `pip install -U lolviz` now. should get 1.2.1. see if py3 works

**Comment by renweibo** [comment]
This works now. Thanks for your update. I verify it on python 3.6.

**Comment by parrt** [comment]
lolviz 1.3 coming soon
