### ISSUE TITLE
Hidden values of nested table

### ISSUE THREAD

**Issue by pytkr** [parrt/lolviz#23]
I find table in lolviz can not show values if cell in one row is a list, as:
```

T = [
    ['11','12','13','14',['a','b','c'],'16']
]
objviz(T)
```
Only the a, b, c are shown and 11, 12, 13, 14, and 16 are not shown, is this configurable? Thanks!

**Comment by parrt** [comment]
Weird. Yep, i only see:
<img width="209" alt="Screen Shot 2019-08-05 at 11 40 24 AM" src="https://user-images.githubusercontent.com/178777/62487116-ddb20980-b775-11e9-962b-c9a1478ba206.png">

**Comment by parrt** [comment]
Ah. actually use `lolviz()` not `objviz()`, @pytkr
